# Generated by Django 4.2 on 2023-04-28 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo_app', '0004_alter_product_image_url'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('total_price', models.IntegerField(null=True)),
                ('status', models.CharField(default='PENDING', max_length=200, null=True)),
                ('payment_method', models.CharField(choices=[('Cash on Delivery', 'Cash on delivery'), ('Esewa', 'esewa')], max_length=200)),
                ('payment_status', models.BooleanField(default=False, max_length=200)),
                ('contact_no', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=50)),
                ('order_data', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
