# Generated by Django 4.2 on 2023-05-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0004_alter_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casarsoul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.FileField(null=True, upload_to='static/uploads')),
            ],
        ),
    ]
